# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - id: kubectl-view-cert
    main: ./cmd/kubectl-view-cert
    binary: kubectl-view-cert
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
    - arm64
    ignore:
    - goos: windows
      goarch: arm64

archives:
- builds:
  - kubectl-view-cert
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE
